export const OPENDETAIL = 'OPENDETAIL'; //打开帖子详情页面
export const CLOSEDETAIL = 'CLOSEDETAIL'; //关闭帖子详情
export const TEST_FAIL = 'TEST_FAIL';
export const TEST_ADD = 'TEST_ADD';
export const GETMAINTOPICSUCCESS = 'GETMAINTOPICSUCCESS'; //获得帖子列表成功
export const TOPICDETAILSUCCESS = 'TOPICDETAILSUCCESS';
export const GETNAVSUCCESS = 'GETNAVSUCCESS';
export const OPENLOADING = 'OPENLOADING';
export const CLOSELOADING = 'CLOSELOADING';

export const OPENUSERPROFILE = 'OPENUSERPROFILE';
export const CLOSEUSERPROFILE = 'CLOSEUSERPROFILE';
export const OPENLOGIN = 'OPENLOGIN';
export const CLOSELOGIN = 'CLOSELOGIN';

export const PAGECHANGE  = 'PAGECHANGE';
export const PAGEDATA = 'PAGEDATA';

export const GETAUTHORSUCCESS = 'GETAUTHORSUCCESS'; //获得作者信息

export const LOGINED = 'LOGINED';
export const UNLOGIN = 'UNLOGIN';
export const ACCESSSUCCESS = 'ACCESSSUCCESS';
export const ACCESSFAIL = 'ACCESSFAIL';

export const OPENSNACKBAR = 'OPENSNACKBAR';
export const CLOSESNACKBAR = 'CLOSESNACKBAR';

export const CHANGETHEMETYPE = 'CHANGETHEMETYPE';

export const ADDTOPICSUCCESS = 'ADDTOPICSUCCESS';

export const COLLECTSUCCESS = 'COLLECTSUCCESS';//收藏成功

export const DECOLLECTSUCCESS = 'DECOLLECTSUCCESS';//取消收藏成功

export const GETMESSAGECOUNTSUCCESS = 'GETMESSAGECOUNTSUCCESS';//获取未读数

export const GETUSERMESSAGESUCCESS = 'GETUSERMESSAGESUCCESS';//获取用户消息

export const LOGOUT = 'LOGOUT';//退出登录
